### ISSUE TITLE
Folder icon issue

### ISSUE THREAD

**Issue by lcmen** [oliverseal/tech49-theme#6]
Hi,
Thanks for great theme. I have a question: should my folder icon looks like this?

![screenshot 2015-05-04 20 20 08](https://cloud.githubusercontent.com/assets/1379988/7459265/012ea85e-f29b-11e4-803c-1556bf06a338.png)

Is it some kind of a glitch or did I do something wrong?

Sublime Text 3, build 3083.

**Comment by dillongrove** [comment]
Also having this issue -- what's the deal with these folder icons?
